name: fev
description: A new Flutter project.

# Mencegah publikasi ke pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/foto1.png
    - assets/foto2.png
    - assets/foto3.png
    - assets/foto4.png
    - assets/email.jpg
    - assets/facebook.png
    - assets/google.png
